<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
      <IsTestProject>true</IsTestProject>
      <IsPackable>false</IsPackable>
      <LangVersion>default</LangVersion>
      <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
      <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
      <TargetFrameworks>net8.0;net10.0;net9.0;net11.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
      <Using Include="Xunit"/>
      <Using Include="AutoFixture"/>
      <Using Include="AutoFixture.Xunit3"/>
      <Using Include="NSubstitute"/>
      <Using Include="AwesomeAssertions"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="AutoFixture.AutoNSubstitute" Version="4.18.1" />
    <PackageReference Include="AutoFixture.Xunit3" Version="4.19.0" />
    <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageReference Include="Verify.XunitV3" Version="31.28.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LayeredCraft.DecoWeaver.Attributes\LayeredCraft.DecoWeaver.Attributes.csproj" />
    <ProjectReference Include="..\..\src\LayeredCraft.DecoWeaver.Generators\LayeredCraft.DecoWeaver.Generators.csproj" />
  </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
        <PackageReference Include="Basic.Reference.Assemblies.Net80" Version="1.8.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[8.0.1, 9.0.0)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net9.0'">
        <PackageReference Include="Basic.Reference.Assemblies.Net90" Version="1.8.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[9.0.19, 10.0.0)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net10.0'">
        <PackageReference Include="Basic.Reference.Assemblies.Net100" Version="1.8.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[10.0.9, 11.0.0)" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net11.0'">
        <PackageReference Include="Basic.Reference.Assemblies.Net110" Version="1.8.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[11.0.0-preview.5.26302.115, 12.0.0-a)" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Cases\**\*.cs" />
        <None Include="Cases\**\*.cs" />
        <None Update="Cases\**\*.cs">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
