//HintName: LayeredCraft.DecoWeaver.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace LayeredCraft.DecoWeaver.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class DecoWeaverInterceptors
    {
        [InterceptsLocation(version: 1, data: "++ogaUd5p3qQhTQ4TFlQJ+QAAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddSingleton&lt;global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>&gt;(IServiceCollection, global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>)</summary>
        internal static IServiceCollection AddSingleton_0<TService>(this IServiceCollection services, TService implementationInstance)
            where TService : class
        {
            var key = DecoratorKeys.For(typeof(global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>), typeof(global::DecoWeaver.Sample.SqlRepository<global::DecoWeaver.Sample.Customer>));
            var capturedInstance = (global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>)(object)implementationInstance;
            services.AddKeyedSingleton<global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>>(key, capturedInstance);
            services.AddSingleton<global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>>(sp =>
            {
                var current = (global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>)sp.GetRequiredKeyedService<global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.LoggingRepository<global::DecoWeaver.Sample.Customer>), current)!;
                current = (global::DecoWeaver.Sample.IRepository<global::DecoWeaver.Sample.Customer>)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.CachingRepository<global::DecoWeaver.Sample.Customer>), current)!;
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }

            public static object ForKeyed(object? userKey, Type serviceType, Type implementationType)
            {
                // Return a tuple that preserves the actual key object (not its string representation)
                // This ensures distinct object keys create distinct nested keys
                return (userKey, serviceType, implementationType);
            }
        }

    }
}