//HintName: LayeredCraft.DecoWeaver.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace LayeredCraft.DecoWeaver.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class DecoWeaverInterceptors
    {
        [InterceptsLocation(version: 1, data: "BUmebHxJMuMvWFskRebYwy8BAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddScoped&lt;global::DecoWeaver.Sample.IRepository<global::Account>, global::DecoWeaver.Sample.Repository<global::Account>&gt;(IServiceCollection, Func&lt;IServiceProvider, global::DecoWeaver.Sample.Repository<global::Account>&gt;)</summary>
        internal static IServiceCollection AddScoped_0<TService, TImplementation>(this IServiceCollection services, Func<IServiceProvider, TImplementation> implementationFactory)
            where TService : class
            where TImplementation : class, TService
        {
            var key = DecoratorKeys.For(typeof(global::DecoWeaver.Sample.IRepository<global::Account>), typeof(global::DecoWeaver.Sample.Repository<global::Account>));
            services.AddKeyedScoped<global::DecoWeaver.Sample.IRepository<global::Account>>(key, (sp, _) => (global::DecoWeaver.Sample.IRepository<global::Account>)implementationFactory(sp));
            services.AddScoped<global::DecoWeaver.Sample.IRepository<global::Account>>(sp =>
            {
                var current = (global::DecoWeaver.Sample.IRepository<global::Account>)sp.GetRequiredKeyedService<global::DecoWeaver.Sample.IRepository<global::Account>>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::DecoWeaver.Sample.IRepository<global::Account>)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.CachingRepository<global::Account>), current)!;
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }

            public static object ForKeyed(object? userKey, Type serviceType, Type implementationType)
            {
                // Return a tuple that preserves the actual key object (not its string representation)
                // This ensures distinct object keys create distinct nested keys
                return (userKey, serviceType, implementationType);
            }
        }

    }
}