//HintName: LayeredCraft.DecoWeaver.Interceptors.ClosedGenerics.g.cs
// <auto-generated />
#nullable enable

namespace System.Runtime.CompilerServices
{
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}

namespace LayeredCraft.DecoWeaver.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using Microsoft.Extensions.DependencyInjection;

    file static class DecoWeaverInterceptors
    {
        [InterceptsLocation(version: 1, data: "+eVDMtaOaEQ72K1TjjzzZfAAAABQcm9ncmFtLmNz")]
        /// <summary>Intercepted: ServiceCollectionServiceExtensions.AddScoped&lt;global::DecoWeaver.Sample.IUserService, global::DecoWeaver.Sample.UserService&gt;(IServiceCollection)</summary>
        internal static IServiceCollection AddScoped_0<TService, TImplementation>(this IServiceCollection services)
            where TService : class
            where TImplementation : class, TService
        {
            var key = DecoratorKeys.For(typeof(global::DecoWeaver.Sample.IUserService), typeof(global::DecoWeaver.Sample.UserService));
            services.AddKeyedScoped<global::DecoWeaver.Sample.IUserService, global::DecoWeaver.Sample.UserService>(key);
            services.AddScoped<global::DecoWeaver.Sample.IUserService>(sp =>
            {
                var current = (global::DecoWeaver.Sample.IUserService)sp.GetRequiredKeyedService<global::DecoWeaver.Sample.IUserService>(key)!;
                // Compose decorators (innermost to outermost)
                current = (global::DecoWeaver.Sample.IUserService)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.UserValidationDecorator), current)!;
                current = (global::DecoWeaver.Sample.IUserService)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.UserAuditDecorator), current)!;
                current = (global::DecoWeaver.Sample.IUserService)ActivatorUtilities.CreateInstance(sp, typeof(global::DecoWeaver.Sample.UserLoggingDecorator), current)!;
                return current;
            });
            return services;
        }

        private static class DecoratorKeys
        {
            public static object For(Type serviceType, Type implementationType)
            {
                var s = serviceType.AssemblyQualifiedName ?? serviceType.FullName ?? serviceType.Name;
                var i = implementationType.AssemblyQualifiedName ?? implementationType.FullName ?? implementationType.Name;
                return string.Concat(s, "|", i);
            }

            public static object ForKeyed(object? userKey, Type serviceType, Type implementationType)
            {
                // Return a tuple that preserves the actual key object (not its string representation)
                // This ensures distinct object keys create distinct nested keys
                return (userKey, serviceType, implementationType);
            }
        }

    }
}